server:
  port: 8080

spring:
  application:
    name: Data Collection
  datasource:
    url: jdbc:mysql://localhost:3306/data-collection-db
    username: haner
    password: gu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG